<?php
/**
 * Zend Framework 2 - PHP-Magazin Routing mit ZF2
 *
 * Beispiele für ZF2 Routing
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       https://github.com/RalfEggert/phpmagazin.routing
 */

/**
 * Layout view script
 *
 * @package    Application
 */

// set header
$this->headTitle('Zend Framework 2 - PHP-Magazin Routing mit ZF2')->setSeparator(' - ')->setAutoEscape(false);
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headLink(array('rel'  => 'shortcut icon', 'href' => $this->basePath() . '/img/favicon.ico'));
$this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap.min.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap-theme.min.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/font-awesome.min.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/styles.css');
$this->inlineScript()->prependFile('/js/bootstrap.min.js', 'text/javascript');
$this->inlineScript()->prependFile('/js/jquery-2.0.3.min.js', 'text/javascript');
?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headStyle(); ?>
</head>
<body>
<div class="top_line"></div>
<header>
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="logo col-xs-2">
                    <a href="/">
                        <img alt="Zend Framework 2" title="Zend Framework 2" src="/img/zf2-logo.png">
                    </a>
                </div>
                <div class="logo-text">
                    <h2><a href="/">PHP-Magazin Routing mit ZF2</a></h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                        data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<?php echo $this->url('home'); ?>">Startseite</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('shop'); ?>">Shop</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Katalog <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="<?php echo $this->url('shop/controller', array('controller' => 'catalogue')); ?>">
                                    Intro
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('shop/controller/action', array('controller' => 'catalogue', 'action' => 'show')); ?>">
                                    Anzeigen
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('shop/controller/action', array('controller' => 'catalogue', 'action' => 'category')); ?>">
                                    Kategorie
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('shop/controller/action', array('controller' => 'catalogue', 'action' => 'offers')); ?>">
                                    Angebote
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Warenkorb <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="<?php echo $this->url('shop/controller', array('controller' => 'basket')); ?>">
                                    Anzeigen
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('shop/controller/action', array('controller' => 'basket', 'action' => 'send')); ?>">
                                    Versenden
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('shop/controller/action', array('controller' => 'basket', 'action' => 'cancel')); ?>">
                                    Löschen
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('shop/controller/action', array('controller' => 'basket', 'action' => 'add')); ?>">
                                    Hinzufügen
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('shop/controller/action', array('controller' => 'basket', 'action' => 'remove')); ?>">
                                    Entfernen
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>

<div class="container">
    <?php echo $this->content; ?>
</div>

<footer id="footer">
    <div class="footer-top"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h4>ZF2 - PHP-Magazin Routing mit ZF2</h4>
                <p>
                    In diesem Projekt finden Sie die lauffähigen Beispiele für
                    den Artikel zum Routing mit dem Zend Framework 2 aus dem
                    PHP Magazin.
                </p>
                <p>
                    <a href="https://plus.google.com/105130475645941839411" target="_blank" class="btn btn-default">
                        Feedback erwünscht!
                    </a>
                    <a href="https://github.com/RalfEggert/phpmagazin.routing" target="_blank" class="btn btn-default">
                        GitHub Repository
                    </a>
                </p>
            </div>
        </div>
    </div>
</footer>

<?php echo $this->inlineScript() ?>
</body>
</html>
