<?php
/**
 * Zend Framework 2 - PHP-Magazin Routing mit ZF2
 *
 * Beispiele für ZF2 Routing
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @link       https://github.com/RalfEggert/phpmagazin.routing
 */

/**
 * namespace definition and usage
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->headTitle('Herzlich Willkommen!');

?>
<div class="jumbotron">
    <h1>Zend Framework 2 - PHP-Magazin Routing mit ZF2</h1>
    <p>
        In diesem Projekt finden Sie die lauffähigen Beispiele für den Artikel
        zum Zend Framework 2 Routing aus dem PHP Magazin.
    </p>
</div>
